# 2. 넘파이(Numpy)

In [1]:
import numpy as np

### 1) np.array()

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
b = np.array([[10, 20, 30], [60, 70 ,80]])
print(b)

[[10 20 30]
 [60 70 80]]


In [7]:
print(b.ndim) #차원 출력
print(b.shape) #크기 출력

2
(2, 3)


In [8]:
print(a.ndim) #차원 출력
print(a.shape) #크기 출력


1
(5,)


### 2) ndarray의 초기화

In [14]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a = np.full((2,2), 7)
print(a)

[[7 7]
 [7 7]]


In [17]:
a = np.eye(3) #대각선으로는 1이고 나머지는 0인 2차원 배열 생성.
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a = np.random.random((2,2)) #임의의 값으로 채워진 배열 생성
print(a)

[[0.9393645  0.65165584]
 [0.66963423 0.80391748]]


### 3) np.arange()

In [20]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### 4) reshape()

In [21]:
a = np.array(np.arange(30).reshape((5, 6)))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5) Numpy 슬라이싱

In [23]:
a = np.array([[1,2,3], [4,5,6]])
b = a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [24]:
b = a[0, :]
print(b)

[1 2 3]


In [25]:
b = a[:,1]
print(b)

[2 5]


### 6) Numpy 정수 인덱싱(integer indexing)

In [26]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2,1], [1,0]]
print(b)

[8 4]


### 7) Numpy 연산

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [28]:
b = x + y # 각 요소에 대해서 더함
# b = np.add(x, y)와 동일함
print(b)

[5 7 9]


In [29]:
b = x - y # 각 요소에 대해서 빼기
# b = np.subtract(x, y)와 동일함
print(b)

[-3 -3 -3]


In [30]:
b = b * x # 각 요소에 대해서 곱셈
# b = np.multiply(b, x)와 동일함
print(b)

[-3 -6 -9]


In [31]:
b = b / x # 각 요소에 대해서 나눗셈
# b = np.divide(b, x)와 동일함
print(b)

[-3. -3. -3.]


In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
