# 텐서 조작하기(Tensor Manipulation) 1
## 넘파이로 텐서 만들기(벡터와 행렬 만들기)

### 1) 1D with Numpy

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t; ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t;  1
Shape of t:  (7,)


### 1-1) Numpy 기초 이해하기

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 
#통해 가져온다.

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[3:] = ', t[:2], t[3:]) # 시작번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2) 2D with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9. ], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 파이토치 텐서 선언하기(PyTorch Tensor Allocation)